Akseiev
one-lov-e/stalk pull request #10
Opened 2022-11-20 11:09 UTC by AKSEIEV

2022-11-20 11:38 UTC, biggujo requested changes
Добра робота. Але:

- приберіть матеріали для banner, бо Ви його не зробили, ці матераіли не відносяться до Pull Request з footer. Для banner потрібна інша гілка.
- Додайте увесь код Вашого footer до ./src/partials/footer.html та приберіть його з index.html. Потім в index.html додайте `<include src="./partials/footer.html"></include>`
- зверніть увагу на позиціонування елементів у footer, приведіть вигляд до макету у десктопній та мобільній версіях: https://imgur.com/a/MnViDxB

2022-11-20 11:38 UTC, biggujo commented on src/index.html
> +          <section>
Не дано клас для секції

2022-11-20 11:38 UTC, biggujo commented on src/index.html
> +        </h2>
```suggestion
        <h2 class="footer-logo">
        <a class="footer-logo-link" href="./index.html"
           > SHOP FOR <br />
          GAMERS
          </a>          
        </h2>
```

2022-11-20 11:38 UTC, biggujo commented on src/sass/index.scss
> +@import 'layout/banner';
Цей текст приберіть. Додайте у `./src/sass/_main.scss` такий рядок:
`@import "footer";`

2022-11-20 11:38 UTC, biggujo commented on src/sass/layout/_footer.scss
> +.footer-meil-item {
```suggestion
.footer-mail-item {
```

2022-11-20 12:37 UTC, one-lov-e approved these changes

2022-11-20 12:37 UTC, one-lov-e approved these changes

2022-11-27 14:37 UTC, biggujo approved these changes
Добре

2022-11-27 14:43 UTC, merged