feature/lines
one-lov-e/stalk pull request #18
Opened 2022-11-22 12:14 UTC by HaidaienkoK

add component lines, replaced variables on the page OP

2022-11-22 13:45 UTC, biggujo requested changes
Добра робота. Прошу виконати такі рекомендації:

- додати margin для ліній: https://imgur.com/a/wjDGegH
- зробити випадне меню абсолютним: https://imgur.com/a/u7mP4RX
- takeOrder.html перейменувати на take-order.html
- виконати усі коментарі, що були дані до коду

2022-11-22 13:45 UTC, biggujo commented on src/partials/lines.html
> +<section class="lines">
Це оформлення, тому це не повноцінна секція з контентом, а лише div
```suggestion
<div class="lines">
```

2022-11-22 13:45 UTC, biggujo commented on src/partials/lines.html
> +</section>
```suggestion
</div>
```

2022-11-22 13:45 UTC, biggujo commented on src/sass/layout/_lines.scss
> +.line_first,
Будь ласка, усі класи запишіть у форматі kebab-case: .line-first, .line-second тощо. Саме через мінус "-"

2022-11-22 13:45 UTC, biggujo commented on src/sass/pages/_take-order.scss
>    .to__product_info {
Будь ласка, усі класи назвіть у форматі kebab-case: .to-product-info, .to-name тощо

2022-11-22 14:48 UTC, HaidaienkoK commented on src/sass/pages/_take-order.scss
>    .to__product_info {
Меню так працює по проекту...

2022-11-24 11:07 UTC, AlbinaKovalchuk approved these changes

2022-11-24 11:07 UTC, AlbinaKovalchuk commented on src/partials/lines.html
> +<section class="lines">
++

2022-11-24 11:22 UTC, AlbinaKovalchuk approved these changes

2022-11-24 17:57 UTC, AlbinaKovalchuk commented on src/sass/layout/_main.scss
>  @import 'buttons'
треба додати крапку з комою

2022-11-27 14:23 UTC, biggujo approved these changes
Добре

2022-11-27 14:24 UTC, one-lov-e approved these changes

2022-11-27 14:25 UTC, merged