Accessories galery
one-lov-e/stalk pull request #23
Opened 2022-11-23 16:48 UTC by TaniaMudryk

лінки на Take Order поки не підключені
лінії тільки код html, взяла в Костянтина

2022-11-25 15:46 UTC, biggujo requested changes
Гарна робота.
Будь ласка, виконайте рекомендації:
- встановити `cursor: pointer` для кнопок-фільтрів: https://imgur.com/a/7ZeyIpe
- та інші

2022-11-25 15:46 UTC, biggujo commented on src/partials/accessories.html
> +            <p class="accessories-over-text">
Тут і далі замість `<br>` використати ряд абзаци `<p>`

2022-11-25 15:46 UTC, biggujo commented on src/sass/pages/_accessories.scss
> +.accessories-btn {
Перенести клас для кнопки у файл для компонентів кнопок: ./src/sass/layout/_buttons.scss

2022-11-26 12:53 UTC, TaniaMudryk commented on src/partials/accessories.html
> +            <p class="accessories-over-text">
не зрозуміла, як це зробити

2022-11-26 12:55 UTC, TaniaMudryk commented on src/sass/pages/_accessories.scss
> +.accessories-btn {
думаю, краще це зробити, коли гілки об'єднають
в мене поки зараз не видно  _buttons.scss

2022-11-27 14:47 UTC, biggujo approved these changes
Добре

2022-11-27 14:53 UTC, merged